name: PR Validation

on:
  pull_request:
    paths:
      - '.github/release-notes/**'

jobs:
  validate-release-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate release notes format
        run: |
          for file in .github/release-notes/*.md; do
            filename=$(basename "$file")
            version="${filename%.*}"
            
            # Check version format
            if [[ ! $version =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Invalid version format in filename: $filename"
              echo "Must be in format v1.0.0.md"
              exit 1
            fi
            
            # Check file content
            if [ ! -s "$file" ]; then
              echo "Release notes file is empty: $filename"
              exit 1
            fi
          done